### ISSUE TITLE
Can't npm install as Missing package version

### ISSUE THREAD

**Issue by s550550550** [goatformat/ftk#1]
Hi, 

Sorry if it's a stupid issue, I'm new to all of this but I tried to npm install and it wouldn't let me as it's missing the package version. I tried cloning in local and installing; and I also tried installing directly from the github link.

Thanks in advance.

**Comment by scheibo** [comment]
To begin with there should probably be a big red "WIP" somewhere in the README, as this project is not completed (I used this project as a distraction when I was burnt out from my work on @pkmn, which will inevitably happen again and I will come back and finish polishing up this project...). However, even upon completion I'm not sure I planned to actually publish the package. https://goatformat.github.io/ftk/sim/ is kind of intended to be the end product here (in addition to research) - the only use cases I can think of for publishing the project are to make it easier for people to create their own UIs (which is completely valid) or leveraging the code to write bots for DuelingBook etc (which I'm less keen to encourage)
